### ISSUE TITLE
Clan Wars

### ISSUE THREAD

**Issue by UnAfraid** [L2JUnity/L2JUnity#1]
Implement the new clan wars.
- Blood war declaration:
- - Clan 1 issues war to Clan 2
- - Clan 2 must kill 5 Clan 1 members in order to activate the war.
- - Once activated the war will never end unless one of clans end it.
- Ending a clan war costs 5k clan reputation.
- When a player kills enemy there is a screen message (Its actually system message i think?)
Enemy = war/siege.

**Comment by Sdw-** [comment]
Pushed !

**Comment by St3eT** [comment]
Good :+1:
